### ISSUE TITLE
product title contains field content delimiters ".."

### ISSUE THREAD

**Issue by ewirch** [FACT-Finder/ff-web-components-demos#2]
![image](https://cloud.githubusercontent.com/assets/1880345/19766967/d6b9730e-9c50-11e6-8f05-ca05789a68fd.png)

**Comment by HJK181** [comment]
The field content delimiters are getting returned by FACT-Finder, this is nothing that should be replaced in the frontend. The behavior of FACT-Finder can be changed by activating a commonClass which replaces the field content delimiters.

**Comment by HJK181** [comment]
See comment above.
